apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-website-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: rm05/ecom-web
          resources:
            limits:
              memory: "128mi"
              cpu: "75m"
            requests:
              memory: "50mi"
              cpu: "1m"
          env:
          - name: DB_HOST
            value: "database-service"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "ecommerce"
          - name: DB_USER
            value: "ecommerce"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: password
          volumeMounts:
          - name: database-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: database-persistent-storage
          persistentVolumeClaim:
            claimName: database-pvc