apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-webapp
  template:
    metadata:
      labels:
        app: ecom-webapp
    spec:
      containers:
        - name: ecom-webapp-container
          image: rm05/ecom-web:v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "120Mi"
              cpu: "75m"
            requests:
              memory: "50Mi"
              cpu: "1m"
          ports:
            - containerPort: 80
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: website-configmap
                key: DB_NAME
          - name: FEATURE_DARK_MODE  
            valueFrom:
              configMapKeyRef:
                name: feature-toggle-config
                key: FEATURE_DARK_MODE  