name: Build and Deploy

run-name: ${{ github.actor }} has pushed changes to ${{ github.event.ref }}

on:
    push:
        branches:
            - 'release/ecom/*'

jobs:
    ecom_build_docker_images:
        runs-on: ubuntu-latest

        defaults:
            run:
              working-directory:  ./learning-app-ecommerce

        steps:
          - name: Checkout code ✅
            uses: actions/checkout@v4

          - name: Set up Docker Buildx 🛠️ 
            uses: docker/setup-buildx-action@v1
    
          - name: Log in to Docker Hub 🔑
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Build and push Docker image for webapp 🐳
            uses: docker/build-push-action@v2
            with:
              context: .
              file: ./learning-app-ecommerce/Dockerfile.app  # spcific for ecom-webapp
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/ecom-web:latest

          - name: Build and push Docker image for mariadb 🐳
            uses: docker/build-push-action@v2
            with:
             context: .
             file: ./learning-app-ecommerce/Dockerfile.db  # spcific for mariadb 
             push: true
             tags: ${{ secrets.DOCKER_USERNAME }}/ecom-db:latest

    ecom_webapp_deploy:
        runs-on: ubuntu-latest
        needs: ecom_build_docker_images

        steps:
          - name: Checkout code ✅
            uses: actions/checkout@v3
    
          - name: Set up Kubectl CLI 🔧
            uses: azure/setup-kubectl@v1
            with:
              version: 'latest'
    
          - name: Set up Helm 🔧
            uses: azure/setup-helm@v1
            with:
              version: 'latest'
    
          - name: Deploy to Kubernetes 
            run: |
              helm upgrade --install ecom-web ./chart \
                --set image.repository=${{ secrets.DOCKER_USERNAME }}/ecom-web \
                --set image.tag=latest
    
    akrc_codeql_scan:
        runs-on: ubuntu-latest
        needs: ecom_webapp_deploy

        steps:
        - name: Checkout ☑️
          uses: actions/checkout@v4

        - name: Initialize CodeQL 🔄
          uses: github/codeql-action/init@v3
          with:
            languages: javascript

        - name: Perform CodeQL Analysis 🔎
          uses: github/codeql-action/analyze@v3
          with:
            category: "language:php,
                        language:html,
                        language:yaml"        