# Default values for ecom-web-chart.
# Deployment values
name: ecomm-website-deployment
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
replicaCount: 1
# Container spec values
containers:
  name: ecomWebAppContainer
  image:
    repository: rm05/ecom-web
    pullPolicy: Always
    tag: v2
    resources:
      limits:
        cpu: "75m"
        memory: "120Mi"
      requests:
        cpu: "1m"
        memory: "50Mi"
    ports:
      containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 5

# Configmap and secret values  
configmap:
  metadata:
    name: website-configmap
  websiteConfigmap:
    data:
      DB_HOST: mariadbService
      DB_PORT: '3306'
      DB_NAME: ecomdb
      DB_USER: ecomdbUser
  featureToggleConfig:
    metadata:
      name: featureToggleConfig
    data:
      FEATURE_DARK_MODE: "true"
secret:
  dbSecrets:
    metadata:
      name: dbSecrets
    DB_PASSWORD: ZHJvd3NzYXA0MzIx

# Autoscaling values
horizontalPodAutoscaler:
  metadata:
    name: website-hpa
    namespace: default
  spec:
    name: ecommWebsiteDeployment
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    metrics:
      resource:
          target:
            type: Utilization
            averageUtilization: 50

# Service values to expose the ecom website
service:
  metadata:
    name: web-service
    labels:
      run: webService
  type: LoadBalancer
  port: 80
  protocol: TCP
  targetPort: 80
  selector:
    app: ecomWebapp