apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.service.metadataName }}
  labels:
    run: {{ .Values.website.service.run }}
spec:
  selector:
    app: {{ .Values.website.service.app }}
  ports:
    - protocol: {{ .Values.website.service.protocol }}
      port: {{ .Values.website.service.port }}
      targetPort: {{ .Values.website.service.targetPort }}
  type: {{ .Values.website.service.type }}