apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.website.horizontalPodAutoscaler.metadataName }}
  namespace: {{ .Values.website.horizontalPodAutoscaler.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.website.horizontalPodAutoscaler.name }}
  minReplicas: {{ .Values.website.horizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.website.horizontalPodAutoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: {{ .Values.website.horizontalPodAutoscaler.type }}
        averageUtilization: {{ .Values.website.horizontalPodAutoscaler.averageUtilization }}