apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.horizontalPodAutoscaler.metadata.name }}
  namespace: {{ .Values.horizontalPodAutoscaler.metadata.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.horizontalPodAutoscaler.spec.name }}
  minReplicas: {{ .Values.horizontalPodAutoscaler.spec.minReplicas }}
  maxReplicas: {{ .Values.horizontalPodAutoscaler.spec.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: {{ .Values.horizontalPodAutoscaler.spec.metrics.resource.target.type }}
        averageUtilization: {{ .Values.horizontalPodAutoscaler.spec.metrics.resource.target.averageUtilization }}