apiVersion: v1
kind: Secret
metadata:
  name: dbsecrets
type: Opaque
data:
  dbPassword: {{ .Values.website.secret.dbSecrets.dbPassword }}
  username: {{ .Values.website.secret.dbSecrets.username}}