apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
spec:
  selector:
    app: mariadb
  ports:
    - protocol: {{ .Values.database.service.protocol }}
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}