apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.database.storage.persistentVolumeName }}
spec:
  capacity:
    storage: {{ .Values.database.storage.size}}
  accessModes:
    - {{ .Values.database.storage.accessModes}}
  persistentVolumeReclaimPolicy: {{ .Values.database.storage.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.database.storage.storageClassName}}
  hostPath:
    path: {{ .Values.database.storage.hostPath}}