apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.mariaDbSecrets.name}}
  namespace: default
type: Opaque
data:
  password: {{ .Values.database.mariaDbSecrets.password }}
  username: {{ .Values.database.mariaDbSecrets.username }}